#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for the genetic query optimizer module
#
# Copyright (c) 1994, Regents of the University of California
#
# src/backend/optimizer/geqo/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/optimizer/ant
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS =	ants_copy.o ants_eval.o ants_main.o ants_pool.o ants_random.o 

include $(top_srcdir)/src/backend/common.mk
